const object = (properties = {}, required = []) => ({ type: 'object', properties, required, additionalProperties: false });
const string = values => ({ type: 'string', ...(values ? { enum: values } : {}) });
const tool = (name, description, inputSchema = object()) => ({ name, description, inputSchema });
const MIRROR_TOOLS = [
  tool('mirror_command', 'Run an explicitly requested local command: getting ready, movie time, favorite this, show my favorites, show my lookbook, take a look photo, save this look, compare looks, retake, leave a note: TEXT, set a timer for N minutes, cancel timer, what can I do here, camera clarity off/natural/bright, blink, raise an eyebrow, look left/right/at me/thoughtful/surprised, smile, set maximum detail, set balanced quality, set efficient quality, use 3D face, use portrait face. Photo capture is a countdown then a review; saving is a separate user request. Commands may start asynchronously: read mirror state to verify completion.', object({ command: string() }, ['command'])),
  tool('get_mirror_state', 'Read current display, voice, camera, garment and player state. No pixels or Spotify metadata.'),
  tool('see_screen', 'Observe the current screen image. Required immediately before every computer action. Spotify content stays local.'),
  tool('computer_action', 'Perform one action on the observed target, then inspect the attached resulting screenshot. Coordinates use 0–1000 on the full image. Each snapshotId permits one action. Never repeat activation because its outcome is off-screen. close_browser returns to mirror.', object({ action: string(['click','double_click','type_text','press_key','scroll','close_browser']), snapshotId: string(), x: { type: 'integer', minimum: 0, maximum: 1000 }, y: { type: 'integer', minimum: 0, maximum: 1000 }, text: string(), key: string(['enter','tab','escape','backspace','space','up','down','left','right','home','end','pageup','pagedown','win','ctrl+a','ctrl+l','ctrl+f','alt+tab']), deltaY: { type: 'integer' } }, ['action'])),
  tool('open_service', 'Open a requested service. Find My opens Apple Find Devices, not friends locations. Sign in directly; never enter account credentials. Spotify opens the local app and its contents cannot be captured.', object({ service: string(['youtube','netflix','spotify','calendar','photos','maps','findmy']) }, ['service'])),
  tool('open_webpage', 'Open a website explicitly requested by the user in the managed browser. HTTP or HTTPS URL.', object({ url: string() }, ['url'])),
  tool('search_web', 'Open web search results in the managed browser.', object({ query: string() }, ['query'])),
  tool('set_display_mode', 'Change the mirror display.', object({ mode: string(['mirror','portal','ar','watch','spotify']) }, ['mode'])),
  tool('set_avatar_position', 'Move the avatar to make room for content.', object({ position: string(['center','left','right','upper','lower']) }, ['position'])),
  tool('control_watch', 'Control the current Watch video player: YouTube, direct media or phone-cast video. Load only a user-supplied HTTP(S) media URL. Read returned player state to verify; acknowledgement is not playback success. Volume is an integer percentage for Watch only, not Spotify or system audio.', object({ action: string(['status','load','play','pause','seek','volume']), url: string(), seconds: { type: 'number', minimum: -60, maximum: 60 }, volume: { type: 'integer', minimum: 0, maximum: 100 } }, ['action'])),
  tool('wardrobe_command', 'Control the local wardrobe photo editor. Commands include add garment, front photo, back photo, take front photo, take back photo, extract clothing, trim top, trim bottom, save, cancel. Check state and review before saving.', object({ command: string() }, ['command'])),
  tool('control_camera', 'Turn the local mirror camera on or off only when requested. Reports actual camera state and permission errors; starting does not prove face or garment tracking. Does not take/save a photo or enable cloud sharing. A pending start is cancelled when the agent task stops; an already active camera is preserved until explicit off.', object({ enabled: { type: 'boolean' } }, ['enabled'])),
  tool('adjust_try_on', 'Adjust the selected garment fit using absolute values or reset defaults. Width/length default to 1; negative offset raises it. Local fit is approximate placement, not sizing or fabric simulation. Live is local camera fit; rendered selects an existing still. Neural requires the configured optional provider and the user-confirmed camera-sharing checkbox. This tool does not request a new still render. Inspect returned mirror state before claiming visibility.', object({ view: string(['live','rendered','neural']), width: { type: 'number', minimum: 0.7, maximum: 1.5 }, length: { type: 'number', minimum: 0.7, maximum: 1.5 }, offset: { type: 'number', minimum: -0.25, maximum: 0.25 }, reset: { type: 'boolean' } })),
  tool('request_try_on', 'Select an available local garment by name. Check returned visible fit state; selection alone is not proof of visibility. No hidden fabric reconstruction or accurate sizing.', object({ garmentName: string() }, ['garmentName']))
];
module.exports = { MIRROR_TOOLS };
